POST http://localhost:3000/api/services
Content-Type: application/json

{ 
   
  
    "name": "Inflatable Toys",
    "description": "Bounce houses, slides, and other inflatable toys for children.",
    "price": 1000,
    "image": "https://images.unsplash.com/photo-1663398073601-55b654139868?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fEluZmxhdGFibGUlMjBUb3lzJTIwcGFydHl8ZW58MHx8MHx8fDA%3D"
}

###

GET http://localhost:3000/api/services
###

GET  http://localhost:3000/api/services/6863ef64b0a8e7c7a4388235

### 
DELETE http://localhost:3000/api/services/6863ef64b0a8e7c7a4388235

###
PUT http://localhost:3000/api/services/6863eef3b0a8e7c7a4388225
Content-Type: application/json

{
    
    "_id": "6863eef3b0a8e7c7a4388225",
    "name": "Security",
    "description": "Professionals to ensure event safety and access control.",
    "price": 700,
    "image": "https://images.unsplash.com/photo-1618371731836-2b9bff9ac72a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDJ8fFNlY3VyaXR5fGVufDB8fDB8fHww"
    
}

###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Pionato",
    "author": "Mikael",
    "description": "joguear bola",
    "guests": 10,
    "location": "Casa do vo",
    "eventDate":  "2025-08-10T20:00:00",
    "budget": 9000,
    "image": "https://es.pinterest.com/pin/655484920791181891/",
    "services": [
        
{
    "name": "Fami",
    "description": "Demonio da Morte ",
    "price": 2000 ,
    "image": "https://es.pinterest.com/pin/655484920791181891/"
    
}
    ]
    
}

###

GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/68605e28dce7c41bab9d0bc3

### 
DELETE http://localhost:3000/api/parties/685f2b4e77e2de3c113459d7

###
PUT http://localhost:3000/api/parties/685dd1224e8c66cbf79f90c9
Content-Type: application/json

{
    "title": "Festa no quarto",
    "author": "Maquima",
    "description": "Role em casa",
    "budget": 9000,
    "image": "https://images.unsplash.com/photo-1665592514154-7970e9b7a105?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTAyfHxhbmltZXxlbnwwfHwwfHx8MA%3D%3D",
    "services": [
        
{
    "name": "000",
    "description": "00",
    "price": 2000 ,
    "image": "https://images.unsplash.com/photo-1748392029321-58793571f850?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    
}
    ]
    
}